file=None
instr=""
file=open(r"C:\Users\Sungshin\PycharmProjects\weel12_file\file","r",encoding='UTF-8')
instr=file.readline()
print(instr,end="")
instr=file.readline()
print(instr,end="")
instr=file.readline()
print(instr,end="")
file.close()